defaults: &defaults
  docker:
    - image: circleci/node:dubnium-browsers

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .next

  deploy:
    docker:
      - image: startupcraftio/circleci-aws-deployment:1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              AWS_DEFAULT_REGION=us-west-2 ANSIBLE_CONFIG=ansible/ansible.cfg ansible-playbook ansible/release-deploy.yml -i ansible/staging --extra-vars "branch=master aws_profile=default" -v
            elif [ "${CIRCLE_BRANCH}" == "demo" ]; then
              AWS_DEFAULT_REGION=us-west-2 ANSIBLE_CONFIG=ansible/ansible.cfg ansible-playbook ansible/release-deploy.yml -i ansible/demo --extra-vars "branch=demo aws_profile=default" -v
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              AWS_DEFAULT_REGION=us-west-2 ANSIBLE_CONFIG=ansible/ansible.cfg ansible-playbook ansible/release-deploy.yml -i ansible/production --extra-vars "branch=production aws_profile=default" -v
            fi

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - deploy:
          requires:
            - prepare
            - build
          filters:
            branches:
              only:
                - master
                - demo
                - production
