env: staging
node_env: production
port: 80
api_host: https://api.humanos.c8.ai
web_url: https://humanos.c8.ai
google_client_id: 331673999257-kfei20bqatcu7jad3er5tmof2re24hh6.apps.googleusercontent.com
sentry_dsn: https://d75883d456344b60845e311008d465aa@sentry.io/1731669
aws_region: us-west-2
cluster: humanos-staging
acquisition_image_name: humanos-acquisition
acquisition_image_repository: 378762170585.dkr.ecr.us-west-2.amazonaws.com/humanos-acquisition
task_role_arn: arn:aws:iam::378762170585:role/ecs/humanos-staging-task-role
execution_role_arn: arn:aws:iam::378762170585:role/ecs/humanos-staging-execution-role
acquisition_cpu: 512
acquisition_memory: 1024
acquisition_container_cpu: 384
acquisition_container_memory: 768
acquisition_desired_count: 1
subnets: ['subnet-085d2c428db407ee1', 'subnet-06690d2827cd6fa5c']
security_groups: ['sg-0b1635efa969d6f2f']
